/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author queza
 */
public class RegistroUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroUsuario
     */
    public RegistroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAlias = new javax.swing.JTextField();
        jRadioButtonHombre = new javax.swing.JRadioButton();
        jRadioButtonMujer = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonSubir = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDPI = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxRol = new javax.swing.JComboBox<>();
        jComboBoxNacionalidad = new javax.swing.JComboBox<>();
        jCheckBoxConfirmar = new javax.swing.JCheckBox();
        jPasswordField = new javax.swing.JPasswordField();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jComboBoxDD = new javax.swing.JComboBox<>();
        jComboBoxMM = new javax.swing.JComboBox<>();
        jTextFieldYYYY = new javax.swing.JTextField();
        jLabelFotografia = new javax.swing.JLabel();
        jCheckBoxMostrar = new javax.swing.JCheckBox();
        jButtonRegistrar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro de Usuario");
        setPreferredSize(new java.awt.Dimension(910, 446));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldEmail.setToolTipText("");
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 203, 380, -1));

        jLabel6.setText("Correo Electronico");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 181, 380, -1));

        jLabel7.setText("Contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 243, -1, -1));

        jLabel9.setText("Confirmar Contraseña");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 243, -1, -1));

        jLabel10.setText("Nacionalidad");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));

        jLabel11.setText("Sobrenombre (Alias)");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 190, -1));

        jTextFieldAlias.setToolTipText("");
        getContentPane().add(jTextFieldAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 190, -1));

        buttonGroup1.add(jRadioButtonHombre);
        jRadioButtonHombre.setText("Hombre");
        getContentPane().add(jRadioButtonHombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 100, -1, -1));

        buttonGroup1.add(jRadioButtonMujer);
        jRadioButtonMujer.setText("Mujer");
        getContentPane().add(jRadioButtonMujer, new org.netbeans.lib.awtextra.AbsoluteConstraints(824, 100, -1, -1));

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 15, -1, -1));

        jLabel2.setText("Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 15, -1, -1));

        jTextFieldApellido.setToolTipText("");
        getContentPane().add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 37, 240, -1));

        jLabel3.setText("Fecha de Nacimiento");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 15, 231, -1));

        jButtonSubir.setText("SUBIR");
        getContentPane().add(jButtonSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 136, -1, -1));

        jTextFieldNombre.setToolTipText("");
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 37, 240, -1));

        jLabel5.setText("DPI");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 77, -1, -1));

        jTextFieldDPI.setToolTipText("");
        getContentPane().add(jTextFieldDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 99, 498, -1));

        jLabel12.setText("Telefono");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        jTextFieldTelefono.setToolTipText("");
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 190, -1));

        jLabel13.setText("Rol");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 200, -1));

        jComboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario Individual", "Usuario Empresarial", "Kiosco" }));
        getContentPane().add(jComboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 200, -1));

        jComboBoxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala", "Alemania", "Italia", "Francia", " " }));
        jComboBoxNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNacionalidadActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 190, -1));

        jCheckBoxConfirmar.setText("Confirmar Campos");
        jCheckBoxConfirmar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBoxConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 160, 20));
        getContentPane().add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 265, 160, -1));
        getContentPane().add(jPasswordFieldConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 265, 160, -1));

        jComboBoxDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DD", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jComboBoxDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 37, 50, -1));

        jComboBoxMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBoxMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMMActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 37, 56, -1));

        jTextFieldYYYY.setText("YYYY");
        jTextFieldYYYY.setToolTipText("");
        getContentPane().add(jTextFieldYYYY, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 37, 50, -1));

        jLabelFotografia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabelFotografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 15, 125, 115));

        jCheckBoxMostrar.setText("Mostrar Contraseña");
        jCheckBoxMostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jCheckBoxMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 370, -1));

        jButtonRegistrar.setText("REGISTRAR");
        jButtonRegistrar.setEnabled(false);
        getContentPane().add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 160, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNacionalidadActionPerformed

    private void jComboBoxMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMMActionPerformed

    private void jCheckBoxConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButtonRegistrar;
    public javax.swing.JButton jButtonSubir;
    public javax.swing.JCheckBox jCheckBoxConfirmar;
    public javax.swing.JCheckBox jCheckBoxMostrar;
    public javax.swing.JComboBox<String> jComboBoxDD;
    public javax.swing.JComboBox<String> jComboBoxMM;
    public javax.swing.JComboBox<String> jComboBoxNacionalidad;
    public javax.swing.JComboBox<String> jComboBoxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelFotografia;
    public javax.swing.JPasswordField jPasswordField;
    public javax.swing.JPasswordField jPasswordFieldConfirm;
    public javax.swing.JRadioButton jRadioButtonHombre;
    public javax.swing.JRadioButton jRadioButtonMujer;
    public javax.swing.JTextField jTextFieldAlias;
    public javax.swing.JTextField jTextFieldApellido;
    public javax.swing.JTextField jTextFieldDPI;
    public javax.swing.JTextField jTextFieldEmail;
    public javax.swing.JTextField jTextFieldNombre;
    public javax.swing.JTextField jTextFieldTelefono;
    public javax.swing.JTextField jTextFieldYYYY;
    // End of variables declaration//GEN-END:variables
}
